<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Ushas-MacBook-Air.local" failures="3" tests="8" name="Test" time="7.521" errors="0" timestamp="2025-03-11T21:14:43 PDT">
  <testcase classname="api.test.UserTests" name="testPostUser" time="3.378"/>
  <testcase classname="api.test.UserTests" name="testGetUser" time="0.511">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testGetUser(UserTests.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testGetUser -->
  <testcase classname="api.test.UserTests" name="testUpdatetUser" time="0.92">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testUpdatetUser(UserTests.java:67)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testUpdatetUser -->
  <testcase classname="api.test.UserTests" name="testDeleteUser" time="0.446">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests.testDeleteUser(UserTests.java:77)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUser -->
  <testcase classname="api.test.DDTests" name="testPostUser" time="0.421"/>
  <testcase classname="api.test.DDTests" name="testPostUser" time="0.431"/>
  <testcase classname="api.test.DDTests" name="testGetUer" time="0.436"/>
  <testcase classname="api.test.DDTests" name="testGetUer" time="0.435"/>
</testsuite> <!-- Test -->
